stages:
  - build
  - test
  - deploy

sast:
  stage: test
  include:
    - template: Security/SAST.gitlab-ci.yml
    - template: Security/SAST-IaC.latest.gitlab-ci.yml
    - template: Security/License-Scanning.gitlab-ci.yml

unit-test-job:
  image: python:3.10-alpine
  stage: test
  script:
    - pip3 install Flask==2.1.0 gunicorn==20.1.0 pydantic==1.8.2 Pillow==8.4.0 requests==2.27.1 beautifulsoup4==4.10.0 pytest==7.1.1
    - python3 -m pytest
  rules:
    - if: $CI_COMMIT_BRANCH
      exists:
        - run.py

docker-build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        tag=""
        echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
      else
        tag=":$CI_COMMIT_REF_SLUG"
        echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
      fi
    - docker build --pull -t "$CI_REGISTRY_IMAGE${tag}" .
    - docker push "$CI_REGISTRY_IMAGE${tag}"
  rules:
    - if: $CI_COMMIT_BRANCH
      exists:
        - Dockerfile

deploy-job:
  stage: deploy
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:latest
  script:
    - docker-compose -f 'docker-compose.yml' --project-name 'wabs-placegeoxormoe' down
    - docker-compose -f 'docker-compose.yml' --project-name 'wabs-placegeoxormoe' up -d
  rules:
    - if: $CI_COMMIT_BRANCH
      exists:
        - docker-compose.yml
