version: "3"

services:
  geoxorplacevapronvapwwebsite:
    image: registry.vapronva.pw/websites/fs_geoxoplace_vapronva_pw-website:latest
    container_name: "web-geoxorplacevapronvapw"
    ports:
      - 6033:80
    networks:
      - "w-geoxorplacevapronvapw-network"
  imagesdownloadergeoxorplace:
    image: registry.vapronva.pw/agents/place_geoxor_moe_canvas_downloader-api_agent:latest
    container_name: "api_agent-place_geoxor_moe_downloader"
    networks:
      - "w-geoxorplacevapronvapw-network"
    volumes:
      - canvasimages-15s:/usr/src/app/board-images-15s
      - canvasimages-60s:/usr/src/app/board-images-60s
  api:
    image: registry.vapronva.pw/api/place_geoxor_moe_altcan-api:latest
    container_name: "api_web-place_geoxor_moe_alternative"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - MASTER_KEY=${MASTER_KEY}
    networks:
      - "w-geoxorplacevapronvapw-network"
    ports:
      - 6032:8000
  web:
    image: registry.vapronva.pw/websites/geoxor_place_vapronva_pw-website:latest
    container_name: "web-geoxor_place_vapronva_pw"
    networks:
      - "w-geoxorplacevapronvapw-network"
    ports:
      - 6031:8000

volumes:
  canvasimages-60s:
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=192.168.75.10,rw,noatime,nolock,soft,rsize=8192,wsize=8192,tcp,timeo=14
      device: "192.168.75.10:/mnt/seagate-4tb-ex7-ws221yth/minio-object_storage/pub.fs.geoxorplace.vapronva.pw/canvas-images/1-minute-interval"
  canvasimages-15s:
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=192.168.75.10,rw,noatime,nolock,soft,rsize=8192,wsize=8192,tcp,timeo=14
      device: "192.168.75.10:/mnt/seagate-4tb-ex7-ws221yth/minio-object_storage/pub.fs.geoxorplace.vapronva.pw/canvas-images/15-seconds-interval"

networks:
  w-geoxorplacevapronvapw-network:
    external: true
